data:
  dt: 6
  train_data_path: '/hkfs/work/workspace/scratch/ke4365-era5_data/era5_subset.zarr'
  valid_data_path: '/hkfs/work/workspace/scratch/ke4365-era5_data/era5_subset.zarr'
  train_subset: 1250
  valid_subset: 20
  prefetch_factor: 2 
  num_workers: 2
  xlat: 720
  xlon: 1440
  lite: True
model:
  hidden_dim: 512
  spatial_hidden_dim_fraction: 0.125
  features_hidden_dim_fraction: 0.5
  mixing_blocks: 3
  model_parallel: True
  patch_size: 60
  stride: 60
  add: False
  positional_encoding: False
  patch_embed: 1
  latent_rollout: 1
  concat: True
  linear_residual: True
  dropout: 0.001
training:
  lr: 0.0001
  lr_embedding: 0.00002
  lr_recovery: 0.00002
  loss: 'L2'
  lr_constant: False
  train_batch: 1
  valid_batch: 1
  grad_clip: 10
  save_dir: '.'
  file_path: '.'
  load_path: '.'
  area_weighted: True 
  tf32: True
model_parallel:
  split: 4
  parallelism: 4
